/**
 * Kern design system theme for Monaco Editor.
 *
 * Mirrors the token palette from global.css (bg-core, bg-surface, grid-bounds,
 * signal-high, signal-low, warn-vector, fault-vector) so the editor feels
 * native to the app rather than a floating VS Code island.
 *
 * Token coverage is comprehensive — every common language construct gets a
 * distinct color so that code reads like the rest of the kern interface:
 * amber for keywords/control, green for strings/values, blue for types,
 * tan for functions, light blue for variables/properties.
 */

import type { editor } from "monaco-editor";

export const KERN_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    // ── Comments ──────────────────────────────────────────────────────────
    { token: "comment", foreground: "4c525e", fontStyle: "italic" },
    { token: "comment.doc", foreground: "5c6370", fontStyle: "italic" },
    { token: "comment.line", foreground: "4c525e", fontStyle: "italic" },
    { token: "comment.block", foreground: "4c525e", fontStyle: "italic" },
    { token: "comment.block.documentation", foreground: "5c6370", fontStyle: "italic" },

    // ── Keywords ──────────────────────────────────────────────────────────
    { token: "keyword", foreground: "f5a04c" },
    { token: "keyword.control", foreground: "f5a04c" },
    { token: "keyword.control.flow", foreground: "f5a04c" },
    { token: "keyword.control.loop", foreground: "f5a04c" },
    { token: "keyword.control.conditional", foreground: "f5a04c" },
    { token: "keyword.control.import", foreground: "f5a04c" },
    { token: "keyword.control.export", foreground: "f5a04c" },
    { token: "keyword.control.trycatch", foreground: "f5a04c" },
    { token: "keyword.operator", foreground: "d4d4d4" },
    { token: "keyword.other", foreground: "f5a04c" },
    { token: "modifier", foreground: "f5a04c" },
    { token: "storage", foreground: "f5a04c" },
    { token: "storage.type", foreground: "f5a04c" },
    { token: "storage.modifier", foreground: "f5a04c" },

    // ── Strings ───────────────────────────────────────────────────────────
    { token: "string", foreground: "4cf5a0" },
    { token: "string.quoted", foreground: "4cf5a0" },
    { token: "string.quoted.single", foreground: "4cf5a0" },
    { token: "string.quoted.double", foreground: "4cf5a0" },
    { token: "string.quoted.triple", foreground: "4cf5a0" },
    { token: "string.template", foreground: "4cf5a0" },
    { token: "string.interpolated", foreground: "d4d4d4" },
    { token: "string.regexp", foreground: "d16969" },
    { token: "string.key", foreground: "9cdcfe" },
    { token: "string.anchor", foreground: "4cf5a0" },
    { token: "string.reference", foreground: "4cf5a0" },
    { token: "regexp", foreground: "d16969" },
    { token: "regexp.key", foreground: "d16969" },
    { token: "regexp.group", foreground: "d7ba7d" },

    // ── Numbers / Constants ───────────────────────────────────────────────
    { token: "number", foreground: "ce9178" },
    { token: "number.hex", foreground: "ce9178" },
    { token: "number.octal", foreground: "ce9178" },
    { token: "number.binary", foreground: "ce9178" },
    { token: "number.float", foreground: "ce9178" },
    { token: "constant", foreground: "4fc1ff" },
    { token: "constant.numeric", foreground: "ce9178" },
    { token: "constant.language", foreground: "569cd6" },
    { token: "constant.language.boolean", foreground: "569cd6" },
    { token: "constant.language.null", foreground: "569cd6" },
    { token: "constant.language.undefined", foreground: "569cd6" },
    { token: "constant.character", foreground: "ce9178" },
    { token: "constant.character.escape", foreground: "d7ba7d" },
    { token: "constant.other", foreground: "4fc1ff" },
    { token: "predefined", foreground: "4fc1ff" },

    // ── Types ─────────────────────────────────────────────────────────────
    { token: "type", foreground: "4fc1ff" },
    { token: "type.identifier", foreground: "4fc1ff" },
    { token: "type.builtin", foreground: "4fc1ff" },
    { token: "type.parameter", foreground: "4fc1ff" },
    { token: "type.argument", foreground: "4fc1ff" },
    { token: "type.module", foreground: "4fc1ff" },
    { token: "enum", foreground: "4fc1ff" },
    { token: "enumMember", foreground: "dcdcaa" },
    { token: "struct", foreground: "4fc1ff" },
    { token: "interface", foreground: "4fc1ff", fontStyle: "italic" },
    { token: "event", foreground: "dcdcaa" },
    { token: "class", foreground: "4fc1ff" },
    { token: "class.identifier", foreground: "4fc1ff" },
    { token: "namespace", foreground: "4fc1ff" },
    { token: "module", foreground: "4fc1ff" },

    // ── Functions / Methods ───────────────────────────────────────────────
    { token: "function", foreground: "dcdcaa" },
    { token: "function.declaration", foreground: "dcdcaa" },
    { token: "function.call", foreground: "dcdcaa" },
    { token: "function.builtin", foreground: "dcdcaa" },
    { token: "function.library", foreground: "dcdcaa" },
    { token: "method", foreground: "dcdcaa" },
    { token: "method.declaration", foreground: "dcdcaa" },
    { token: "method.call", foreground: "dcdcaa" },
    { token: "constructor", foreground: "dcdcaa" },
    { token: "decorator", foreground: "dcdcaa" },
    { token: "annotation", foreground: "dcdcaa" },

    // ── Variables / Properties ────────────────────────────────────────────
    { token: "variable", foreground: "9cdcfe" },
    { token: "variable.other", foreground: "9cdcfe" },
    { token: "variable.other.readwrite", foreground: "9cdcfe" },
    { token: "variable.other.constant", foreground: "4fc1ff" },
    { token: "variable.other.member", foreground: "9cdcfe" },
    { token: "variable.other.property", foreground: "9cdcfe" },
    { token: "variable.parameter", foreground: "9cdcfe" },
    { token: "variable.language", foreground: "569cd6" },
    { token: "variable.language.this", foreground: "569cd6" },
    { token: "variable.language.self", foreground: "569cd6" },
    { token: "variable.language.super", foreground: "569cd6" },
    { token: "parameter", foreground: "9cdcfe" },
    { token: "property", foreground: "9cdcfe" },
    { token: "property.declaration", foreground: "9cdcfe" },
    { token: "attribute.name", foreground: "9cdcfe" },
    { token: "attribute.value", foreground: "4cf5a0" },
    { token: "identifier", foreground: "9cdcfe" },
    { token: "identifier.key", foreground: "9cdcfe" },

    // ── Tags (HTML / XML) ────────────────────────────────────────────────
    { token: "tag", foreground: "569cd6" },
    { token: "tag.id", foreground: "569cd6" },
    { token: "tag.class", foreground: "569cd6" },
    { token: "metatag", foreground: "dcdcaa" },
    { token: "metatag.content", foreground: "4cf5a0" },

    // ── Delimiters / Operators ────────────────────────────────────────────
    { token: "delimiter", foreground: "d4d4d4" },
    { token: "delimiter.html", foreground: "808080" },
    { token: "delimiter.xml", foreground: "808080" },
    { token: "punctuation", foreground: "d4d4d4" },
    { token: "punctuation.definition", foreground: "d4d4d4" },
    { token: "punctuation.separator", foreground: "d4d4d4" },
    { token: "punctuation.terminator", foreground: "d4d4d4" },
    { token: "operator", foreground: "d4d4d4" },
    { token: "operator.sql", foreground: "f5a04c" },
    { token: "operator.logical", foreground: "f5a04c" },
    { token: "operator.comparison", foreground: "d4d4d4" },
    { token: "operator.arithmetic", foreground: "d4d4d4" },
    { token: "operator.assignment", foreground: "d4d4d4" },

    // ── Support ───────────────────────────────────────────────────────────
    { token: "support.function", foreground: "dcdcaa" },
    { token: "support.type", foreground: "4fc1ff" },
    { token: "support.constant", foreground: "4fc1ff" },
    { token: "support.variable", foreground: "9cdcfe" },
    { token: "support.class", foreground: "4fc1ff" },

    // ── Markdown ──────────────────────────────────────────────────────────
    { token: "keyword.md", foreground: "f5a04c" },
    { token: "string.md", foreground: "4cf5a0" },
    { token: "variable.md", foreground: "9cdcfe" },
    { token: "heading", foreground: "569cd6", fontStyle: "bold" },
    { token: "heading.1", foreground: "569cd6", fontStyle: "bold" },
    { token: "heading.2", foreground: "569cd6", fontStyle: "bold" },
    { token: "heading.3", foreground: "569cd6", fontStyle: "bold" },
    { token: "heading.4", foreground: "569cd6", fontStyle: "bold" },
    { token: "heading.5", foreground: "569cd6", fontStyle: "bold" },
    { token: "heading.6", foreground: "569cd6", fontStyle: "bold" },
    { token: "emphasis", foreground: "d4d4d4", fontStyle: "italic" },
    { token: "strong", foreground: "d4d4d4", fontStyle: "bold" },
    { token: "quote", foreground: "4c525e", fontStyle: "italic" },
    { token: "code", foreground: "4cf5a0" },
    { token: "code.fenced", foreground: "4cf5a0" },
    { token: "code.inline", foreground: "4cf5a0" },
    { token: "list", foreground: "f5a04c" },
    { token: "list.unnumbered", foreground: "f5a04c" },
    { token: "list.numbered", foreground: "f5a04c" },
    { token: "link", foreground: "4cf5a0" },
    { token: "link.reference", foreground: "4cf5a0" },
    { token: "link.definition", foreground: "4cf5a0" },
    { token: "separator", foreground: "4c525e" },

    // ── Diff ──────────────────────────────────────────────────────────────
    { token: "diff.inserted", foreground: "4cf5a0" },
    { token: "diff.removed", foreground: "f54c4c" },
    { token: "diff.header", foreground: "569cd6" },
    { token: "diff.range", foreground: "569cd6" },
    { token: "diff.separator", foreground: "4c525e" },

    // ── Invalid / Deprecated ──────────────────────────────────────────────
    { token: "invalid", foreground: "f54c4c", fontStyle: "underline" },
    { token: "invalid.deprecated", foreground: "4c525e", fontStyle: "strike" },
    { token: "deprecated", foreground: "4c525e", fontStyle: "strike" },

    // ── Custom Monarch: .env ──────────────────────────────────────────────
    { token: "env-comment", foreground: "4c525e", fontStyle: "italic" },
    { token: "env-keyword", foreground: "f5a04c" },
    { token: "env-key", foreground: "9cdcfe" },
    { token: "env-separator", foreground: "d4d4d4" },
    { token: "env-value", foreground: "4cf5a0" },
    { token: "env-variable", foreground: "f5a04c" },
    { token: "env-string", foreground: "4cf5a0" },

    // ── Custom Monarch: .properties ───────────────────────────────────────
    { token: "properties-comment", foreground: "4c525e", fontStyle: "italic" },
    { token: "properties-key", foreground: "9cdcfe" },
    { token: "properties-separator", foreground: "d4d4d4" },
    { token: "properties-value", foreground: "4cf5a0" },
    { token: "properties-escape", foreground: "d7ba7d" },
    { token: "properties-continuation", foreground: "4c525e" },

    // ── Custom Monarch: .gitignore / .dockerignore ────────────────────────
    { token: "ignore-comment", foreground: "4c525e", fontStyle: "italic" },
    { token: "ignore-negation", foreground: "f5a04c" },
    { token: "ignore-directory", foreground: "569cd6" },
    { token: "ignore-wildcard", foreground: "f5a04c" },
    { token: "ignore-anchored", foreground: "4cf5a0" },
    { token: "ignore-pattern", foreground: "d4d4d4" },

    // ── Custom Monarch: .ini / .cfg / .conf ───────────────────────────────
    { token: "ini-comment", foreground: "4c525e", fontStyle: "italic" },
    { token: "ini-section", foreground: "f5a04c", fontStyle: "bold" },
    { token: "ini-key", foreground: "9cdcfe" },
    { token: "ini-separator", foreground: "d4d4d4" },
    { token: "ini-value", foreground: "4cf5a0" },
    { token: "ini-boolean", foreground: "569cd6" },

    // ── Custom Monarch: .log ──────────────────────────────────────────────
    { token: "log-timestamp", foreground: "4c525e" },
    { token: "log-level-error", foreground: "f54c4c" },
    { token: "log-level-warn", foreground: "f5a04c" },
    { token: "log-level-info", foreground: "4cf5a0" },
    { token: "log-level-debug", foreground: "4c525e" },
    { token: "log-level-trace", foreground: "4c525e" },
    { token: "log-level-fatal", foreground: "f54c4c" },
    { token: "log-ip", foreground: "569cd6" },
    { token: "log-path", foreground: "4cf5a0" },
    { token: "log-number", foreground: "ce9178" },
    { token: "log-string", foreground: "4cf5a0" },
    { token: "log-stacktrace", foreground: "4c525e" },
  ],
  colors: {
    "editor.background": "#050506",
    "editor.foreground": "#d4d4d4",
    "editorCursor.foreground": "#4cf5a0",
    "editor.selectionBackground": "#264f78",
    "editor.inactiveSelectionBackground": "#264f7844",
    "editor.selectionHighlightBackground": "#264f7855",
    "editor.wordHighlightBackground": "#264f7844",
    "editor.wordHighlightStrongBackground": "#264f7866",
    "editor.lineHighlightBackground": "#0b0c10",
    "editorLineNumber.foreground": "#4c525e",
    "editorLineNumber.activeForeground": "#4cf5a0",
    "editorBracketMatch.background": "#0b0c10",
    "editorBracketMatch.border": "#4c525e",
    "editorWidget.background": "#0b0c10",
    "editorWidget.border": "#161920",
    "editorWidget.foreground": "#d4d4d4",
    "editorIndentGuide.background": "#161920",
    "editorIndentGuide.activeBackground": "#4c525e",
    "editorRuler.foreground": "#161920",
    "editorCodeLens.foreground": "#4c525e",
    "editorOverviewRuler.border": "#161920",
    "editorGutter.background": "#050506",
    "editorError.foreground": "#f54c4c",
    "editorWarning.foreground": "#f5a04c",
    "editorInfo.foreground": "#4fc1ff",
    "editorHint.foreground": "#4c525e",
    "editorWhitespace.foreground": "#16192055",
    "minimap.background": "#050506",
    "minimap.selectionHighlight": "#264f7844",
    "minimap.findMatchHighlight": "#f5a04c44",
    "scrollbar.shadow": "#050506",
    "scrollbar.background": "#050506",
    "scrollbarSlider.background": "#161920",
    "scrollbarSlider.hoverBackground": "#4c525e",
    "scrollbarSlider.activeBackground": "#4c525e",
    "tab.activeBackground": "#0b0c10",
    "tab.inactiveBackground": "#050506",
    "tab.activeForeground": "#e4e4e4",
    "tab.inactiveForeground": "#4c525e",
    "tab.border": "#161920",
    "tab.activeBorder": "#4cf5a0",
    "tab.activeBorderTop": "#4cf5a0",
    "tab.hoverBackground": "#0b0c1033",
    "tab.unfocusedActiveBackground": "#050506",
    "tab.unfocusedInactiveBackground": "#050506",
    "tab.unfocusedActiveForeground": "#d4d4d4",
    "editorGroupHeader.tabsBackground": "#050506",
    "editorGroupHeader.tabsBorder": "#161920",
    "editorGroup.border": "#161920",
    "editorHoverWidget.background": "#0b0c10",
    "editorHoverWidget.border": "#161920",
    "editorSuggestWidget.background": "#0b0c10",
    "editorSuggestWidget.border": "#161920",
    "editorSuggestWidget.selectedBackground": "#264f78",
    "editorSuggestWidget.foreground": "#d4d4d4",
    "editorSuggestWidget.highlightForeground": "#4cf5a0",
    "editorBracketHighlight.foreground1": "#f5a04c",
    "editorBracketHighlight.foreground2": "#4fc1ff",
    "editorBracketHighlight.foreground3": "#4cf5a0",
    "editorBracketHighlight.foreground4": "#f54c4c",
    "editorBracketHighlight.foreground5": "#ce9178",
    "editorBracketHighlight.foreground6": "#569cd6",
    "editorBracketHighlight.unexpectedBracket.foreground": "#f54c4c",
    "statusBar.background": "#0b0c10",
    "statusBar.foreground": "#4c525e",
    "statusBar.border": "#161920",
    "statusBarItem.activeBackground": "#264f78",
    "statusBarItem.hoverBackground": "#0b0c10",
  },
};
