/**
 * Kern design system theme for Monaco Editor.
 *
 * Mirrors the token palette from global.css (bg-core, bg-surface, grid-bounds,
 * signal-high, signal-low, warn-vector, fault-vector) so the editor feels
 * native to the app rather than a floating VS Code island.
 */

import type { editor } from "monaco-editor";

export const KERN_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    // Core syntax tokens
    { token: "comment", foreground: "4c525e", fontStyle: "italic" },
    { token: "keyword", foreground: "f5a04c" },
    { token: "keyword.control", foreground: "f5a04c" },
    { token: "keyword.operator", foreground: "d4d4d4" },
    { token: "keyword.other", foreground: "f5a04c" },
    { token: "string", foreground: "4cf5a0" },
    { token: "string.quoted", foreground: "4cf5a0" },
    { token: "string.key", foreground: "9cdcfe" },
    { token: "number", foreground: "ce9178" },
    { token: "type", foreground: "4fc1ff" },
    { token: "type.identifier", foreground: "4fc1ff" },
    { token: "type.builtin", foreground: "4fc1ff" },
    { token: "function", foreground: "dcdcaa" },
    { token: "function.declaration", foreground: "dcdcaa" },
    { token: "method", foreground: "dcdcaa" },
    { token: "variable", foreground: "9cdcfe" },
    { token: "variable.other", foreground: "9cdcfe" },
    { token: "variable.parameter", foreground: "9cdcfe" },
    { token: "parameter", foreground: "9cdcfe" },
    { token: "property", foreground: "9cdcfe" },
    { token: "attribute.name", foreground: "9cdcfe" },
    { token: "attribute.value", foreground: "4cf5a0" },
    { token: "tag", foreground: "569cd6" },
    { token: "tag.id", foreground: "569cd6" },
    { token: "tag.class", foreground: "569cd6" },
    { token: "delimiter", foreground: "d4d4d4" },
    { token: "delimiter.html", foreground: "808080" },
    { token: "delimiter.xml", foreground: "808080" },
    { token: "metatag", foreground: "ddcaa0" },
    { token: "metatag.content", foreground: "4cf5a0" },
    { token: "namespace", foreground: "4fc1ff" },
    { token: "regexp", foreground: "d16969" },
    { token: "regexp.key", foreground: "d16969" },
    { token: "regexp.group", foreground: "d7ba7d" },
    { token: "annotation", foreground: "dcdcaa" },
    { token: "decorator", foreground: "dcdcaa" },
    { token: "identifier", foreground: "9cdcfe" },
    { token: "identifier.key", foreground: "9cdcfe" },
    { token: "operator", foreground: "d4d4d4" },
    { token: "operator.sql", foreground: "f5a04c" },
    { token: "predefined", foreground: "4fc1ff" },
    { token: "constant", foreground: "4fc1ff" },
    { token: "constant.numeric", foreground: "ce9178" },
    { token: "constant.language", foreground: "569cd6" },
    { token: "constant.character", foreground: "ce9178" },
    { token: "string.regexp", foreground: "d16969" },
    { token: "support.function", foreground: "dcdcaa" },
    { token: "support.type", foreground: "4fc1ff" },
    { token: "support.constant", foreground: "4fc1ff" },
    { token: "support.variable", foreground: "9cdcfe" },

    // Markdown-specific
    { token: "keyword.md", foreground: "f5a04c" },
    { token: "string.md", foreground: "4cf5a0" },
    { token: "variable.md", foreground: "9cdcfe" },

    // Diff
    { token: "diff.inserted", foreground: "4cf5a0" },
    { token: "diff.removed", foreground: "f54c4c" },
    { token: "diff.header", foreground: "569cd6" },
  ],
  colors: {
    "editor.background": "#050506",
    "editor.foreground": "#d4d4d4",
    "editorCursor.foreground": "#4cf5a0",
    "editor.selectionBackground": "#264f78",
    "editor.inactiveSelectionBackground": "#264f7844",
    "editor.selectionHighlightBackground": "#264f7855",
    "editor.wordHighlightBackground": "#264f7844",
    "editor.wordHighlightStrongBackground": "#264f7866",
    "editor.lineHighlightBackground": "#0b0c10",
    "editorLineNumber.foreground": "#4c525e",
    "editorLineNumber.activeForeground": "#4cf5a0",
    "editorBracketMatch.background": "#0b0c10",
    "editorBracketMatch.border": "#4c525e",
    "editorWidget.background": "#0b0c10",
    "editorWidget.border": "#161920",
    "editorWidget.foreground": "#d4d4d4",
    "editorIndentGuide.background": "#161920",
    "editorIndentGuide.activeBackground": "#4c525e",
    "editorRuler.foreground": "#161920",
    "editorCodeLens.foreground": "#4c525e",
    "editorOverviewRuler.border": "#161920",
    "editorGutter.background": "#050506",
    "editorError.foreground": "#f54c4c",
    "editorWarning.foreground": "#f5a04c",
    "editorInfo.foreground": "#4fc1ff",
    "editorHint.foreground": "#4c525e",
    "editorWhitespace.foreground": "#16192055",
    "minimap.background": "#050506",
    "minimap.selectionHighlight": "#264f7844",
    "minimap.findMatchHighlight": "#f5a04c44",
    "scrollbar.shadow": "#050506",
    "scrollbar.background": "#050506",
    "scrollbarSlider.background": "#161920",
    "scrollbarSlider.hoverBackground": "#4c525e",
    "scrollbarSlider.activeBackground": "#4c525e",
    "tab.activeBackground": "#0b0c10",
    "tab.inactiveBackground": "#050506",
    "tab.activeForeground": "#e4e4e4",
    "tab.inactiveForeground": "#4c525e",
    "tab.border": "#161920",
    "tab.activeBorder": "#4cf5a0",
    "tab.activeBorderTop": "#4cf5a0",
    "tab.hoverBackground": "#0b0c1033",
    "tab.unfocusedActiveBackground": "#050506",
    "tab.unfocusedInactiveBackground": "#050506",
    "tab.unfocusedActiveForeground": "#d4d4d4",
    "editorGroupHeader.tabsBackground": "#050506",
    "editorGroupHeader.tabsBorder": "#161920",
    "editorGroup.border": "#161920",
    "editorHoverWidget.background": "#0b0c10",
    "editorHoverWidget.border": "#161920",
    "editorSuggestWidget.background": "#0b0c10",
    "editorSuggestWidget.border": "#161920",
    "editorSuggestWidget.selectedBackground": "#264f78",
    "editorSuggestWidget.foreground": "#d4d4d4",
    "editorSuggestWidget.highlightForeground": "#4cf5a0",
    "editorBracketHighlight.foreground1": "#f5a04c",
    "editorBracketHighlight.foreground2": "#4fc1ff",
    "editorBracketHighlight.foreground3": "#4cf5a0",
    "editorBracketHighlight.foreground4": "#f54c4c",
    "editorBracketHighlight.foreground5": "#ce9178",
    "editorBracketHighlight.foreground6": "#569cd6",
    "editorBracketHighlight.unexpectedBracket.foreground": "#f54c4c",
    "statusBar.background": "#0b0c10",
    "statusBar.foreground": "#4c525e",
    "statusBar.border": "#161920",
    "statusBarItem.activeBackground": "#264f78",
    "statusBarItem.hoverBackground": "#0b0c10",
  },
};
